import "./globals.css";
import { Inter } from "next/font/google";

import { Suspense } from "react";
import Loading from "./loading";

import Navbar from "./components/NavBar";
import Footer from "./components/Footer";
import { Providers } from "./components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <Navbar />
          <Providers>{children}</Providers>
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
